### DISCUSSION TITLE
Traefik Reverse Proxy

### DISCUSSION THREAD

**Discussion by billyors** [lostb1t/replex#34] [Q&A]
Hi there 👋
Big fan of the project so far. 

I'm trying to configure my reverse proxy. I'm not sure why but this app keeps hitting a `502 bad gateway` error. I have a few other apps that are behind the same proxy and use the same config. Is there any chance something special is required to get replex working out of the box with Traefik?

My custom URL is added as `https://replex.custom.domain:3001` in the Network settings. 

Config in docker compose.
```
replex:
    image: ghcr.io/sarendsen/replex:latest
    container_name: replex
    environment:
      REPLEX_HOST: http://plex:32400
    ports:
      - 3001:80
    restart: always
    depends_on:
      - plex
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.replex-rtr.entrypoints=https"
      - "traefik.http.routers.replex-rtr.rule=Host(`replex.custom.domain`)"
      - "traefik.http.routers.replex-rtr.tls=true"
      ## HTTP Services
      - "traefik.http.routers.replex-rtr.service=replex-svc"
      - "traefik.http.services.replex-svc.loadbalancer.server.port=3001"
```
Any assistance is appreciated!

Thanks.
