### ISSUE TITLE
Server is unreachable from Clients

### ISSUE THREAD

**Issue by Lokilicious** [lostb1t/replex#114]
Hi, i set up everything according to the readme and accessing replex directly via port 3001 works fine. But my clients cannot connect to the server. (i.e. libraries don't load)

Only if i manually put in the replex ip and port in the client it connects. 

My docker-compose.yml:

```
---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Vienna
      - VERSION=docker
      - PLEX_CLAIM=X
    volumes:
      - ./config/plex:/config
      - /media/storage/tvshows:/tv
      - /media/storage/movies:/movies
      - /media/storage/plex_test:/test
      - /media/storage/anime:/anime
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: unless-stopped
    ports:
      - 32400:32400
    networks:
      plex_network:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
    volumes:
      - ./config/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped
    networks:
      plex_network:
  plex-meta-manager:
    image: lscr.io/linuxserver/plex-meta-manager:latest
    container_name: plex-meta-manager
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Vienna
      - PMM_CONFIG=/config/config.yml #optional
      - PMM_TIME=05:00 #optional
      #- PMM_RUN=True #optional
      - PMM_TEST=False #optional
      - PMM_DEBUG=False
      - PMM_NO_MISSING=False #optional
      - PMM_COLLECTIONS_ONLY=True
      #- PMM_OVERLAYS_ONLY=True
      #- PMM_RUN_LIBRARIES=Filme
      - PMM_NO_COUNTDOWN=True
    volumes:
      - ./config/pmm:/config
    restart: unless-stopped
  plex-image-cleanup:
    image: meisnate12/plex-image-cleanup
    container_name: plex-image-cleanup
    environment:
      - TZ=Europe/Vienna
      - PLEX_PATH=/plex
      - SCHEDULE=07:00|weekly(monday)
      - PHOTO_TRANSCODER=True
      - EMPTY_TRASH=True
      - CLEAN_BUNDLES=True
      - OPTIMIZE_DB=True
      - PLEX_URL=http://server.lan:32400
      - PLEX_TOKEN=X
      - MODE=remove
    volumes:
      - ./config/plex-image-cleanup:/config
      - "./config/plex/Library/Application Support/Plex Media Server:/plex"
    restart: unless-stopped
    networks:
      plex_network:
  replex:
    image: ghcr.io/lostb1t/replex:latest
    container_name: replex
    environment:
      REPLEX_HOST: http://server.lan:32400
      REPLEX_CACHE_TTL: 600
    ports:
      - 3001:80
    restart: unless-stopped
    depends_on:
      - plex
    networks:
      plex_network:

networks:
  plex_network:
    external: true
```
