### ISSUE TITLE
Setting REPLEX_REDIRECT_STREAMS: true leads to error when starting the container

### ISSUE THREAD

**Issue by Lokilicious** [lostb1t/replex#117]
Error thrown when restarting the container:

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.replex.environment.REPLEX_REDIRECT_STREAMS contains true, which is an invalid type, it should be a string, number, or a null
```

docker-compose.yml
```
  replex:
    image: ghcr.io/lostb1t/replex:latest
    container_name: replex
    environment:
      REPLEX_HOST: http://server.lan:32400
      REPLEX_CACHE_TTL: 600
      REPLEX_REDIRECT_STREAMS: true
    ports:
      - 3001:80
    restart: unless-stopped
    depends_on:
      - plex
    networks:
      plex_network:
```
