### ISSUE TITLE
Error using transcode fallback

### ISSUE THREAD

**Issue by Xstasy** [lostb1t/replex#150]
```
version: "3"
services:
  replex:
    image: ghcr.io/lostb1t/replex:latest
    container_name: replex
    environment:
      REPLEX_HOST: http://172.21.0.20:32400
      REPLEX_TOKEN: ***REDACTED***
      REPLEX_DISABLE_USER_STATE: false
      REPLEX_FORCE_MAXIMUM_QUALITY: true
      REPLEX_FORCE_DIRECT_PLAY_FOR: 4k
      REPLEX_VIDEO_TRANSCODE_FALLBACK_FOR: 1080
    restart: unless-stopped
    networks:
      plex:
        ipv4_address: 172.21.0.40
networks:
  plex:
    external: true
```

Deploys and starts with the error:
```
thread 'main' panicked at src/main.rs:14:54:
called `Result::unwrap()` on an `Err` value: Error { tag: Tag(Default, 1), profile: Some(Profile(Uncased { string: "default" })), metadata: Some(Metadata { name: "`REPLEX_` environment variable(s)", source: None, provide_location: Some(Location { file: "src/config.rs", line: 144, col: 24 }), interpolater:  }), path: ["video_transcode_fallback_for"], kind: InvalidType(Unsigned(1080), "a string"), prev: None }
```
