### ISSUE TITLE
Plex Playback issues

### ISSUE THREAD

**Issue by jl94x4** [lostb1t/replex#55]
Okay a few days ago I opened an issue which I can no longer find, relating to playback issues, and after a few tests I've determined is caused by Replex/as a byproduct of Replex. 

When I disable REPLEX my friend has no issues watching files, however with REPLEX enabled, his shows/movies cut out every 5minutes, sometimes not even giving the option to resume and/or skipping to the next episode randomly.

Can you give me any guidance on what may possibly cause this? To the best of my knowledge I have REPLEX set up correctly.

**Comment by jl94x4** [comment]
I did try remote access and via the same url, both worked with no issues with replex disabled.

**Comment by jl94x4** [comment]
He's tried plex web, mobile (android) and also the plex Windows app too.

**Comment by jl94x4** [comment]
> Did you try using redirect streams?

I haven't. I'll be honest, I'm not sure how to use that.

**Comment by jl94x4** [comment]
http://ip:32400

**Comment by jl94x4** [comment]
> Do you by any change use the force_maximum_quality setting? If so I solved an issue with subtitles. Might try the latest version

I'm gonna re-test tomorrow, this could be the issue. I'll report back.

**Comment by jl94x4** [comment]
Getting more and more reports of this happening.

I asked around, and none of them have used subtitles at all. Not sure what the issue is.

**Comment by jl94x4** [comment]
> https://ip.plex.direct:32400

This doesn't load for me either.

**Comment by Metuant** [comment]
Seeing similar behavior on Samsung for Plex client (Tizen)

**Comment by jl94x4** [comment]
Yes, can confirm that removing REPLEX and going back to just remote access fixes the issue.

**Comment by billyors** [comment]
I don't know if it's the same issue being reported here. But I found that on Roku, my playback streams will end early as if they were completed. About 5 minutes into an episode or movie (often times x265/hevc, x264 seems unaffected) the stream will end and act as if it completed the whole title. PMS debug logs aren't helpful here. But I looked at the Roku logs and I can see it marking the stream as "completed" prematurely. Is this the same behavior other clients are seeing?
What's interesting is that browser, HTPC and Android don't seem to have this issue.

I found that I could workaround the Roku issue by disabling bridge networking on plex and using host networking instead. Then replex points to the plex host ip:port and it seems to workaround the issue. Now Roku streams are completing.

**Comment by jl94x4** [comment]
> I don't know if it's the same issue being reported here. But I found that on Roku, my playback streams will end early as if they were completed. About 5 minutes into an episode or movie (often times x265/hevc, x264 seems unaffected) the stream will end and act as if it completed the whole title. PMS debug logs aren't helpful here. But I looked at the Roku logs and I can see it marking the stream as "completed" prematurely. Is this the same behavior other clients are seeing? What's interesting is that browser, HTPC and Android don't seem to have this issue.
> 
> I found that I could workaround the Roku issue by disabling bridge networking on plex and using host networking instead. Then replex points to the plex host ip:port and it seems to workaround the issue. Now Roku streams are completing.

Sounds similar I'm not using Docker for Plex though.

**Comment by Metuant** [comment]
Re-routed - seems to have helped - will read the docs more closely next time, thank you for a great tool!

**Comment by billyors** [comment]
Hoping for the solution here too.
I routed the above paths with traefik and I'm still seeing the issue.

**Comment by Metuant** [comment]
> @Metuant just to be clear
> 
> Routing
> 
> /video/:/transcode/universal/session /library/parts
> 
> Solved the issue for you?

Correct

**Comment by jl94x4** [comment]
Can someone explain how you reroute? The readme isn't that clear and in unsure what to do now.

**Comment by billyors** [comment]
> > Hoping for the solution here too.
> > I routed the above paths with traefik and I'm still seeing the issue.
> 
> Is it in specific case? Like only when transcoding or with subtitles or just always?

Always with hevc files on Roku. Regardless of subtitles on or off its killing the playback after about 5 minutes. I have everything in mkv files so Roku is having to direct stream. The behavior is consistent where it acts as if the file has completed playback and takes you to the next episode or movie selection screen.

**Comment by jl94x4** [comment]
> > > Hoping for the solution here too.
> > > I routed the above paths with traefik and I'm still seeing the issue.
> > 
> > 
> > Is it in specific case? Like only when transcoding or with subtitles or just always?
> 
> Always with hevc files on Roku. Regardless of subtitles on or off its killing the playback after about 5 minutes. I have everything in mkv files so Roku is having to direct stream. The behavior is consistent where it acts as if the file has completed playback and takes you to the next episode or movie selection screen.

Sounds like my case. How do you go about re-routing? I generally have no idea.

**Comment by billyors** [comment]
> > > > Hoping for the solution here too.
> > > > I routed the above paths with traefik and I'm still seeing the issue.
> > > 
> > > 
> > > Is it in specific case? Like only when transcoding or with subtitles or just always?
> > 
> > 
> > Always with hevc files on Roku. Regardless of subtitles on or off its killing the playback after about 5 minutes. I have everything in mkv files so Roku is having to direct stream. The behavior is consistent where it acts as if the file has completed playback and takes you to the next episode or movie selection screen.
> 
> Sounds like my case. How do you go about re-routing? I generally have no idea.

This is entirely dependent on your reverse proxy tool. I'm using traefik which allows you to set labels on docker containers for specific routing rules. I have the following in place. But, this doesn't solve my playback issues.

```
version: '3.8'
services:
  traefik:
    ...
  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    ...
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex-rtr.entrypoints=https"
      - "traefik.http.routers.plex-rtr.rule=Host(`replex.custom.domain`) && (PathPrefix(`/video/:/transcode/universal/session`) || PathPrefix(`/library/parts`))"
      - "traefik.http.routers.plex-rtr.tls=true"
      - "traefik.http.services.plex-svc.loadbalancer.server.port=32400"
  replex:
    image: ghcr.io/lostb1t/replex:latest
    container_name: replex
    ...
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.replex-rtr.entrypoints=https"
      - "traefik.http.routers.replex-rtr.rule=Host(`replex.custom.domain`) && !(PathPrefix(`/video/:/transcode/universal/session`) || PathPrefix(`/library/parts`))"
      - "traefik.http.routers.replex-rtr.tls=true"
      - "traefik.http.services.replex-svc.loadbalancer.server.port=80"
```

This essentially says these two paths should be routed directly to plex. Then, that replex should exclude these paths from its routing rules.
